/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0pSMmhlUkVMcCtlM3hIWDZyUFNPMWRwQ3ZHcXJZL0NFMk1iS1BzRWpWYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZnpJUHhkSFROeUlOZXJKWWgwVFN4TS9jdTFsZTRuaTB0azNHbVRiUFhCUT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnRkwxNUxoc05vbTRpbHVvOW9qbmprSVBiekorbFoyYmJlMUxkYWluVkhrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI3Q1BzL2pmTWdzY3Q1QklRT1Q2ekRlMXlDejduUHdaMEVjcWNnbkN2OWdJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlFNGhrN3R1QWtqSVpvR1VUQ1krTVU5U1V6SWxUQmJBakFrZG5TdkZHMEE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ilg5UEN6VGtiRUNjeXdnQ2JUcS9aQmlmRnJvZGdaM3RBc2Qrd1R3RDZTamM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEhPTGNoVVFyTmY1V0FhWjZuSzdUTVEvZ2hHOEhmbEJ6RUQxN0ZIbGYxaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibTZFYThCTStrRHl3Sk5QS0g3OU9RMnppOFlObGprMDIrYjdXb0w2N2JuWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJoSVlDTUxCeHYzNWs5b21hUVFLUlhxNzhTbFdFRmpjZnBjaTdUVU8zdTA4RzhhZFNqRGZNOFZRTitqUWJFZjVFMTV1anFwSXpkYmJZdUpETEY5SURnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTIsImFkdlNlY3JldEtleSI6IjZreDExODBHbFNQT0JlU2gyUURBNm1hMHBOVWppNGFyN25hbGVwUDg2ejA9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzM4MzMyNjk1QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjRDNzMyODg1MTAwQ0E4NEY1NjU2RUE0NzkyREE3QjhGIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzAyNzc5MjR9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDczODMzMjY5NUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIwNTMxNTBFODM3NTFCNzZGNTZBRjYzN0FFMUIxMDUzMiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMwMjc3OTI3fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJCLUtkRXo5QVFHbU0tZ0d1VWlxVGRRIiwicGhvbmVJZCI6IjA5ZDllNjZhLWY0NWQtNDg4OS05MmFlLWMyOWQ0ZmQxNzM4MCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJzZnFNWE5OTEFiZ3JhcmdIcEYyaGlCRTR6TTg9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS21zRjhzZHFwL0NCbEhNa01KUDkvQnJhZE93PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlNaVFlBTFpMIiwibWUiOnsiaWQiOiIyNTQ3MzgzMzI2OTU6NDBAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoia2lkb2h0ZWNoIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNMYXZ5S01FRVBqamg3a0dHQVVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJlelpuSTRnTTIxL3dYYlJUY1AxWkNzMHRDVndLVy9QTk9uRFhrbVpKYlhJPSIsImFjY291bnRTaWduYXR1cmUiOiJzSGlLQXlRVVNEdXMyS29lUFhrdWVaT2JJM2NHcnQvdTBCaEZQRkJpL2krUWM0WUM3RzA0Y0dFOURSRGM3YXFMM2NEdkVFTGtKMkE3L0NyUzZGTzBDUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiN2NQTHRXcHE0T0xKYlljM05jZ2tlSkJLeUdEMUgyemhJaEdKVEthem4xTzBOM1R4QlFjN1FHMXJnYzFyQWxqajlWQnA2WlA5VW4xclExd2J2aXhjQ2c9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3MzgzMzI2OTU6NDBAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWHMyWnlPSUROdGY4RjIwVTNEOVdRck5MUWxjQ2x2enpUcHcxNUptU1cxeSJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMDI3Nzg5NCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFBTE8ifQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254114018035';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
